# Generated by Django 3.2 on 2023-02-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '01. User Types',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=0)),
                ('read', models.BooleanField(default=0)),
                ('update', models.BooleanField(default=0)),
                ('delete', models.BooleanField(default=0)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usertype')),
            ],
            options={
                'verbose_name_plural': '02. Permissions',
            },
        ),
    ]
