# Generated by Django 3.2 on 2023-02-28 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '01. Role',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_finance', models.BooleanField(default=0)),
                ('read_finance', models.BooleanField(default=0)),
                ('update_finance', models.BooleanField(default=0)),
                ('delete_finance', models.BooleanField(default=0)),
                ('create_account', models.BooleanField(default=0)),
                ('read_account', models.BooleanField(default=0)),
                ('update_account', models.BooleanField(default=0)),
                ('delete_account', models.BooleanField(default=0)),
                ('create_leads', models.BooleanField(default=0)),
                ('read_leads', models.BooleanField(default=0)),
                ('update_leads', models.BooleanField(default=0)),
                ('delete_leads', models.BooleanField(default=0)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
            options={
                'verbose_name_plural': '02. Permissions',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '03. Company User',
            },
        ),
    ]
