# Generated by Django 3.2 on 2023-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='create',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='read',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='permission',
            name='update',
            field=models.BooleanField(),
        ),
    ]
