# Generated by Django 4.1.4 on 2023-03-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='create_hrm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='create_service',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='delete_hrm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='delete_service',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='manage_lead',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_hrm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_service',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_hrm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_service',
            field=models.BooleanField(default=0),
        ),
    ]
