# Generated by Django 3.2 on 2023-02-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230214_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.usertype'),
        ),
    ]
