# Generated by Django 4.1.4 on 2023-03-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_create_service_permission_create_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='manage_lead',
            new_name='manage_leads',
        ),
    ]
