# Generated by Django 3.2 on 2023-02-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_permission_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='user_type',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='user_type',
            new_name='role',
        ),
    ]
