# Generated by Django 4.1.4 on 2023-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_manage_lead_permission_manage_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='manage_company',
            field=models.BooleanField(default=0),
        ),
    ]
