# Generated by Django 3.2 on 2023-02-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230214_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='create',
            new_name='delete_finance',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='delete',
            new_name='read_finance',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='read',
            new_name='update_finance',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='update',
        ),
        migrations.AddField(
            model_name='permission',
            name='create_finance',
            field=models.BooleanField(default=0),
        ),
    ]
