# Generated by Django 3.2 on 2023-03-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_permission_manage_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user',
        ),
    ]
