# Generated by Django 3.2 on 2023-03-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20230312_1504'),
        ('leads', '0008_leadfiles_created'),
        ('account', '0006_auto_20230312_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
