# Generated by Django 3.2 on 2023-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230215_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '01. Role'},
        ),
        migrations.AddField(
            model_name='permission',
            name='create_account',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='create_leads',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='delete_account',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='delete_leads',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_account',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_leads',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_account',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_leads',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='create_finance',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete_finance',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='read_finance',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='update_finance',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
