# Generated by Django 3.2 on 2023-02-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20230224_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='create_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='create_finance',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='create_leads',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete_finance',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='delete_leads',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='read_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='read_finance',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='read_leads',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='update_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='update_finance',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='permission',
            name='update_leads',
            field=models.BooleanField(default=0),
        ),
    ]
