# Generated by Django 3.2 on 2023-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='assigned_to',
            field=models.ManyToManyField(to='account.CompanyUser'),
        ),
    ]
