# Generated by Django 3.2 on 2023-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leads_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '04. Lead Sources',
            },
        ),
    ]
