# Generated by Django 3.2 on 2023-03-03 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsource',
            options={'verbose_name_plural': '03. Lead Sources'},
        ),
        migrations.AlterModelOptions(
            name='leadstage',
            options={'verbose_name_plural': '02. Lead Stage'},
        ),
        migrations.CreateModel(
            name='LeadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '06. Lead Notes',
            },
        ),
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '04. Activity Log',
            },
        ),
        migrations.CreateModel(
            name='LeadCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('called_by', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '05. Lead Call',
            },
        ),
    ]
