# Generated by Django 3.2 on 2023-03-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20230303_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_file/')),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '06. Lead Files',
            },
        ),
    ]
