# Generated by Django 3.2 on 2023-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfiles',
            name='added_by',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
