# Generated by Django 3.2 on 2023-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadfiles_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfiles',
            name='title',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
