# Generated by Django 3.2 on 2023-03-03 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadfiles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfiles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
