# Generated by Django 3.2 on 2023-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_auto_20230312_1441'),
        ('leads', '0008_leadfiles_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='assigned_to',
            field=models.ManyToManyField(to='hrm.Employee'),
        ),
    ]
