# Generated by Django 4.0.3 on 2023-03-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_leads_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='source',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='stage',
        ),
    ]
