# Generated by Django 4.0.3 on 2023-03-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_leads_source_remove_leads_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource'),
        ),
        migrations.AddField(
            model_name='leads',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadstage'),
        ),
    ]
