# Generated by Django 3.2 on 2023-03-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20230308_1253'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '01. Clients'},
        ),
    ]
