# Generated by Django 3.2 on 2023-03-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_vatable'),
        ('finance', '0002_auto_20230308_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='grand_total',
            new_name='invoice_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
