# Generated by Django 3.2 on 2023-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_vatable'),
        ('finance', '0003_auto_20230308_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': '01. Invoices'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name_plural': '02. Receipts'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deduction_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='previous_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vatable_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
