# Generated by Django 3.2 on 2023-03-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20230314_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
