# Generated by Django 3.2 on 2023-06-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productstatement'),
        ('finance', '0010_alter_invoice_customer_alter_invoiceproduct_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbatch'),
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_quantity', models.IntegerField()),
                ('service_price', models.FloatField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.service')),
            ],
        ),
    ]
