# Generated by Django 4.1.4 on 2023-03-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='type',
            field=models.CharField(blank=True, default='salary', max_length=255, null=True),
        ),
    ]
