# Generated by Django 3.2 on 2023-03-12 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_department_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name_plural': '05. Designation'},
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hrm.designation'),
            preserve_default=False,
        ),
    ]
