# Generated by Django 3.2 on 2023-03-12 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_auto_20230312_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField(blank=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.monthsetup')),
            ],
            options={
                'verbose_name_plural': '05. Holiday',
            },
        ),
    ]
