# Generated by Django 3.2 on 2023-03-12 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_permission_manage_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0006_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.permission'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
