# Generated by Django 3.2 on 2023-03-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_auto_20230312_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
