# Generated by Django 3.2 on 2023-03-16 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_remove_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='is_absent',
        ),
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
