# Generated by Django 3.2 on 2023-03-16 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_auto_20230316_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='date',
        ),
        migrations.CreateModel(
            name='LeaveDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=220)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.leave')),
            ],
            options={
                'verbose_name_plural': '02. Leave Dates',
            },
        ),
    ]
