# Generated by Django 3.2 on 2023-03-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_auto_20230316_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default='sd', max_length=100),
            preserve_default=False,
        ),
    ]
