# Generated by Django 3.2 on 2023-03-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_logsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.monthsetup'),
        ),
    ]
