# Generated by Django 3.2 on 2023-03-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_companyuser'),
        ('hrm', '0014_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.permission'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.monthsetup'),
        ),
    ]
