# Generated by Django 4.0.3 on 2023-03-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_auto_20230320_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='emp_password',
        ),
    ]
