# Generated by Django 4.1.4 on 2023-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0017_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
