# Generated by Django 3.2 on 2023-05-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0019_alter_salary_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAttendanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '02. Attendance Users',
            },
        ),
        migrations.CreateModel(
            name='DeviceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('att_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.deviceattendanceuser')),
            ],
            options={
                'verbose_name_plural': '02. Attendance',
            },
        ),
    ]
