# Generated by Django 3.2 on 2023-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_deviceattendance_deviceattendanceuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceattendance',
            old_name='timestamp',
            new_name='punchin_timestamp',
        ),
        migrations.AddField(
            model_name='deviceattendance',
            name='punchout_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
