# Generated by Django 3.2 on 2023-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0021_auto_20230512_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
            ],
        ),
    ]
