# Generated by Django 3.2 on 2023-05-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0022_devicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='port',
            field=models.IntegerField(),
        ),
    ]
