# Generated by Django 3.2 on 2023-05-12 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0024_auto_20230512_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
