# Generated by Django 3.2 on 2023-05-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0025_deviceattendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceattendanceuser',
            name='uid',
            field=models.IntegerField(max_length=100),
        ),
    ]
