# Generated by Django 3.2 on 2023-05-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0026_alter_deviceattendanceuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceattendanceuser',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
