# Generated by Django 3.2 on 2023-05-14 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0027_alter_deviceattendanceuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
