# Generated by Django 3.2 on 2023-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0030_deviceattendanceuser_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthsetup',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
