# Generated by Django 3.2 on 2023-05-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0031_monthsetup_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthsetup',
            old_name='status',
            new_name='is_active',
        ),
    ]
