# Generated by Django 3.2 on 2023-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_manage_lead_permission_manage_leads'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_to',
        ),
        migrations.AddField(
            model_name='todo',
            name='task_to',
            field=models.ManyToManyField(to='account.CompanyUser'),
        ),
    ]
