# Generated by Django 4.1.4 on 2023-03-11 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20230310_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 18, 52, 28, 952007, tzinfo=datetime.timezone.utc)),
        ),
    ]
