# Generated by Django 4.1.4 on 2023-03-10 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_alter_logsheet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 18, 58, 22, 541853, tzinfo=datetime.timezone.utc)),
        ),
    ]
