# Generated by Django 4.1.4 on 2023-03-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_alter_logsheet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsheet',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
