# Generated by Django 4.1.4 on 2023-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_alter_logsheet_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_email', models.CharField(max_length=255)),
                ('company_contact_number', models.CharField(max_length=255)),
                ('company_bank_name', models.CharField(max_length=255)),
                ('company_account_number', models.CharField(max_length=255)),
                ('company_esewa_number', models.CharField(max_length=255)),
                ('company_khalti_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '03. Company Setup',
            },
        ),
        migrations.AlterModelOptions(
            name='logsheet',
            options={'verbose_name_plural': '01. Log Sheet'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': '02. To Do'},
        ),
    ]
