# Generated by Django 4.1.4 on 2023-03-11 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_company_alter_logsheet_options_alter_todo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
