# Generated by Django 4.1.4 on 2023-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_company_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_account_number',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_esewa_number',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_khalti_number',
            field=models.IntegerField(max_length=255),
        ),
    ]
