# Generated by Django 4.1.4 on 2023-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_company_company_logo_company_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_esewa_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_khalti_number',
            field=models.IntegerField(),
        ),
    ]
