# Generated by Django 4.1.4 on 2023-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_alter_company_company_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_account_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_bank_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_esewa_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_khalti_number',
        ),
        migrations.AddField(
            model_name='company',
            name='payment_details',
            field=models.TextField(blank=True),
        ),
    ]
