# Generated by Django 4.1.4 on 2023-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_remove_company_company_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_terms',
            field=models.TextField(),
        ),
    ]
