# Generated by Django 3.2 on 2023-03-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0019_auto_20230312_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogSheet',
        ),
    ]
