# Generated by Django 3.2 on 2023-05-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0020_delete_logsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(default=1, upload_to='company_images/'),
            preserve_default=False,
        ),
    ]
