# Generated by Django 3.2 on 2023-05-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0021_company_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='signature',
        ),
    ]
