# Generated by Django 3.2 on 2023-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0022_remove_company_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('sms_username', models.CharField(max_length=100)),
                ('sms_password', models.CharField(max_length=100)),
                ('campaign', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '04. Company Credentials',
            },
        ),
    ]
