# Generated by Django 3.2 on 2023-05-16 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
