# Generated by Django 3.2 on 2023-05-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_credentials_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='sms_password',
            new_name='api_key',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='sms_username',
        ),
    ]
