# Generated by Django 3.2 on 2023-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '01. Products',
            },
        ),
    ]
