# Generated by Django 3.2 on 2023-03-08 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_productunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': '02. Products Category'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name_plural': '03. Products Unit'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productunit'),
        ),
    ]
