# Generated by Django 3.2 on 2023-03-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230308_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_vatable',
            field=models.BooleanField(default=True),
        ),
    ]
