# Generated by Django 3.2 on 2023-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_vatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
