# Generated by Django 3.2 on 2023-06-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatement',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
