# Generated by Django 3.2 on 2023-06-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productstatement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatement',
            name='remarks',
            field=models.TextField(default='dsad'),
            preserve_default=False,
        ),
    ]
