# Generated by Django 3.2 on 2023-06-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productstatement_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_batch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255)),
                ('service_price', models.FloatField()),
                ('service_description', models.TextField(blank=True, null=True)),
                ('is_vatable', models.BooleanField(default=True)),
                ('product_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productunit')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': '01. Services',
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_batch', models.CharField(blank=True, max_length=255, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': '01. Product Batch',
            },
        ),
    ]
