# Generated by Django 3.2 on 2023-06-09 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstatement',
            name='product',
        ),
        migrations.AddField(
            model_name='productstatement',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbatch'),
        ),
    ]
