# Generated by Django 3.2 on 2023-06-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230609_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='product_unit',
            new_name='service_unit',
        ),
    ]
