# Generated by Django 3.2 on 2023-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_product_unit_service_service_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='purchase_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
