# Generated by Django 3.2 on 2023-06-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productbatch_purchase_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStatement',
        ),
    ]
